### PR TITLE
Improve user search in saml_login_complete method.

### PR DESCRIPTION
**Pull request by juancs**
Add mnethostid to the search condition in order to benefit from the uniqueindex (mnethostid, username) in user table.

Recreated as #541 was closed accidentally.

### CODE REVIEW

**Comment by kabalin** [comment]
@juancs you need to rebase the patch on MOODLE_39_STABLE branch (it is default now, not master), the auth class moved to classes directory.

**Comment by juancs** [comment]
@kabalin i don't know how to push the rebase without destroying first the branch in my repository... and this will close the pull request:

```
git push origin mnetuser-jota:mnetuser
To github.com:juancs/moodle-auth_saml2.git
 ! [rejected]          mnetuser-jota -> mnetuser (non-fast-forward)
```

Any help? :)

**Comment by kabalin** [comment]
> git push origin mnetuser-jota:mnetuser

Just push to same branch with `-f` param, i.e. `git push origin mnetuser-jota:mnetuser -f`

**Comment by juancs** [comment]
@kabalin Thanx for the trick. I've changed the base branch also... hope this helps :)

**Review by kabalin — APPROVED** [review]
Looks good to me, thanks.

**Pull request merged**
