### PR TITLE
#101 Prevent access to users who are either suspended or deleted

### PR DESCRIPTION
**Pull request by praj**
This is to fix bug #101 which currently allows users to login to Moodle even if their account is either suspended or deleted (though a user with a deleted account will encounter a PHP exception).

### CODE REVIEW

**Comment by brendanheywood** [comment]
Thanks heaps @praj, a few bits of feedback:

* [ ] Conceptually a deleted account is like not having an account in the first place. So I'm thinking that a better approach would be to exclude deleted accounts from the query here:

https://github.com/catalyst/moodle-auth_saml2/pull/102/files#diff-1ce357dc6036d2c85dcc86ba34816421R282

If a user has been deleted, and the autocreate option is on, then I'd expect a new account to be created and for them to get logged in as normal.

* [ ] If the account has been suspended then I think this is worth having a new language pack item saying as much so there is no confusion.

* [ ] can you please make sure travis stays green eg https://travis-ci.org/catalyst/moodle-auth_saml2/builds/225870578

**Comment by praj** [comment]
No worries, I think I'm getting there, let me know how this looks and I think the Travis failures were due to some trailing whitespace which I've removed.

**Comment by praj** [comment]
@brendanheywood are you able to advise why Travis is failing on build jobs 151.6 and 151.15? It seems to be to do with the environment (Postgres) and not necessarily the commit/changes?

**Comment by brendanheywood** [comment]
thanks @praj yeah that postgres error is unrelated, I'll fix that. Code is cool I'll merge it in, thanks!

**Pull request merged**
