### PR TITLE
Closes #213 - Implements missing CI tests, fixes all errors and some warnings.

### LINKED ISSUE #213: Apply full CI tests
Some tests are being ignored, and causing issues such as #212 and #214 

I suggest turning on the tests again and fix the errors (and possible most warnings)

### PR DESCRIPTION
**Pull request by roperto**

### CODE REVIEW

**Comment by danmarsden** [comment]
don't like this much:
https://github.com/catalyst/moodle-auth_saml2/pull/217/commits/d91f713e8ba240e4d46d0be9d779e6523088e06b#diff-d9e5efe20fcedbeffb6f6bf3fb565d87R43

makes it hard to read the sql... - what's the reason for it?

**Comment by roperto** [comment]
@danmarsden mostly to reduce code duplication, makes it easier when you change the structure of the table and need to quickly find everywhere that references it.

I renamed the constant to make it a bit more readable, let me know what you think.

**Comment by roperto** [comment]
This https://github.com/catalyst/moodle-auth_saml2/commit/d91f713e8ba240e4d46d0be9d779e6523088e06b#diff-d9e5efe20fcedbeffb6f6bf3fb565d87L61 would read better if was using the DML API

**Comment by danmarsden** [comment]
still don't like it tbh - Changing table names is not something you would be doing often I would hope, and the name of the table is unique enough to be able to find it without needing a constant.

**Pull request merged**
