### PR TITLE
Improve test

### PR DESCRIPTION
**Pull request by kabalin**
This patch includes:
* Fixing #591 
* Removing excessive tester.php
* Fix passive test logic, so it actually show attributes after sucessful passive login.
* Small visual improvements to raw page (make more intuitive which IdP attributes dump belong):

image

### CODE REVIEW

**Comment by kabalin** [comment]
Pinging @danmarsden, given comment in #619 You guys are not interested in this one that actually fixes a number of issues with test page?

**Comment by doctorlard** [comment]
Hi @kabalin - I for one think this is a good contrib but I'm not "in charge" around here :-)

**Comment by doctorlard** [comment]
For the record this PR addresses issue #550

**Comment by danmarsden** [comment]
sorry - forgot this one was still here! - the other one was a fast quick review that required less brain power.....

**Comment by danmarsden** [comment]
I had to go back and look to see why I didn't merge this earlier - I did review it but had asked the team here if we were doing any automatic testing/smoketests on the tester file that we needed to update... no one got back to me so... I assume we aren't and I've merged it in - also cherry-picked to our older branch too.

**Pull request merged**
