### PR TITLE
Fix core files unit test

### PR DESCRIPTION
**Pull request by golenkovm**
This is a fix for #537

### CODE REVIEW

**Comment by golenkovm** [comment]
With the patch in place the testcase is passing:
```
root@f5f1a3f62cb1:/siteroot# vendor/bin/phpunit files/tests/externallib_test.php                  
Moodle 4.0dev (Build: 20210330), f0eb6a5729b64318bd9d794e440ac400b9240602
Php: 7.4.3, mysqli: 5.7.31, OS: Linux 5.4.0-70-generic x86_64
PHPUnit 9.5.2 by Sebastian Bergmann and contributors.

......                                                              6 / 6 (100%)

Time: 00:01.416, Memory: 66.50 MB

OK (6 tests, 15 assertions)
```

**Comment by golenkovm** [comment]
Hey @danmarsden 

Could you please have a look at this PR once you have a chance.

Kind regards,
Mikhail

**Comment by danmarsden** [comment]
Thanks @golenkovm 

@sammarshallou - do you have any thoughts here? - I'm not convinced the patch is right - if request_method is not set at all, shouldn't we be ignoring the login check as well?

eg maybe something like:
```
if (empty($_SERVER['REQUEST_METHOD']) || $_SERVER['REQUEST_METHOD'] !== 'GET')

**Comment by sammarshallou** [comment]
hi @danmarsden - yes I agree with you, your version of the fix looks correct to me, thanks (sorry for causing the bug)

**Comment by danmarsden** [comment]
Thanks @sammarshallou - @golenkovm could you please update the PR with that change?

**Comment by golenkovm** [comment]
Thanks @danmarsden
The patch is amended.
Sorry for not looking at it in details.
Cheers

**Pull request merged**
