### PR TITLE
Fix #322: Test functionality not working

### LINKED ISSUE #322: Test functionality not working in Moodle 3.6
When trying to use the test functionality from Manage Authentication, no IdPs show in the list to test.  Using the direct link (https://<URL>/auth/saml2/test.php?login=true), we get the following error:

Exception - Could not find the metadata of an IdP with entity ID '<random id>'

Debug info: 
Error code: generalexceptionmessage

×Stack trace:
line 135 of /auth/saml2/extlib/simplesamlphp/modules/saml/lib/Auth/Source/SP.php: SimpleSAML_Error_Exception thrown
line 328 of /auth/saml2/extlib/simplesamlphp/modules/saml/lib/Auth/Source/SP.php: call to sspmod_saml_Auth_Source_SP->getIdPMetadata()
line 431 of /auth/saml2/extlib/simplesamlphp/modules/saml/lib/Auth/Source/SP.php: call to sspmod_saml_Auth_Source_SP->startSSO()
line 193 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Auth/Source.php: call to sspmod_saml_Auth_Source_SP->authenticate()
line 161 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Auth/Simple.php: call to SimpleSAML_Auth_Source->initLogin()
line 103 of /auth/saml2/extlib/simplesamlphp/lib/SimpleSAML/Auth/Simple.php: call to SimpleSAML\Auth\Simple->login()
line 72 of /auth/saml2/test.php: call to SimpleSAML\Auth\Simple->requireAuth()

However, if you display the IdP button, the site will go to the SSO (ADFS in this case) without issue.

Not a total showstopper, but the testing is awesome for making sure you get the Attributes mapped correctly :-)

Thanks!
-Jesse

### PR DESCRIPTION
**Pull request by leonstr**
On the test page you select the IdP to test with but the list of IdPs wasn't
populating correctly.  tester.php now constructs an associative array of
display name and entity ID for each IdP from the array returned by
auth_saml2_get_idps().  classes/form/testidpselect.php:definition() was
iterating through the passed array looking for active IdPs.  This now just
read the passed 'idpentities' with tester.php calling auth_saml2_get_idps()
with $active = true instead.

### CODE REVIEW

**Comment by astamant** [comment]
I'm also having this issue, any updates on this?

**Comment by astamant** [comment]
I'm also having this issue, following.

**Comment by LoveBug** [comment]
This patch also should be backported to the 27-34 branch as the issue it resolves is present there as well.

**Comment by brendanheywood** [comment]
I just did some work on other issues with the tester, I think this pr may be redundant now

**Pull request closed without merging**
