### PR TITLE
Change install.xml and file perms to fix unit tests. Fixes issue #320 and #323

### PR DESCRIPTION
**Pull request by kristian-94**
Minor changes to install.xml that fix unit tests in totara 10.19, see issue #320

### CODE REVIEW

**Comment by danmarsden** [comment]
I think I would have preferred to see this was done using xmldb editor rather than hand-editing the install.xml... any chance you could open this in moodle's xmldb editor and use that to save it to make sure it has fixed anything else up?

**Comment by kristian-94** [comment]
> I think I would have preferred to see this was done using xmldb editor rather than hand-editing the install.xml... any chance you could open this in moodle's xmldb editor and use that to save it to make sure it has fixed anything else up?

Hi @danmarsden , I did use the xmldb editor to make this change, the only thing I removed was the version date that it changed, `<XMLDB PATH="auth/saml2/db" VERSION="20180308"`
I wanted to change as little code as possible to get it passing this unit test.

**Comment by kristian-94** [comment]
@danmarsden I noticed that travis is failing because of the new permissions that the unit test requires on the files, the travis error is: 

> $ phpenv config-rm xdebug.ini
> File xdebug.ini removed from /home/travis/.phpenv/versions/7.0/etc/conf.d.
> before_install.5
> 0.02s$ echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
> 0.00s$ tests/idp/simplesamlphp.sh
> /home/travis/.travis/functions: line 104: tests/idp/simplesamlphp.sh: Permission denied
> The command "tests/idp/simplesamlphp.sh" failed and exited with 126 during .

I wonder what you think is the best way to resolve that conflict?

**Comment by danmarsden** [comment]
Haven't seen that before sorry - bit crazy busy so haven't had a chance to investigate - the patch makes sense though, and so I've merged it anyway. In future I'd suggest leaving the version date change because it shows that you made the change using xmldb to the person reviewing the patch :-)

**Pull request merged**
