### PR TITLE
Removed Behat hook to take screenshot on failure #416

### PR DESCRIPTION
**Pull request by sammarshallou**
Removes the Behat hook that takes a screenshot on failure. When you have the plugin installed, this applies after every failure from every Behat file (even those not related to auth_saml2) and also it crashes on Windows because of hard-coded /tmp path. Since Behat already has a facility to take screenshots on failure anyway (which works on all platforms), the hook should simply be removed IMO.

### CODE REVIEW

**Comment by danmarsden** [comment]
seems to make sense - I suspect we need to remove this line at the same time:
https://github.com/catalyst/moodle-auth_saml2/blob/master/tests/behat/behat_auth_saml2.php#L30

any chance you could update the patch to remove that as well?

thanks!

**Comment by danmarsden** [comment]
seems to make sense - I suspect we need to remove this line at the same time:
https://github.com/catalyst/moodle-auth_saml2/blob/master/tests/behat/behat_auth_saml2.php#L30

any chance you could update the patch to remove that as well?

thanks!

**Comment by sammarshallou** [comment]
Thanks! You're right, that line doesn't appear to be used now, sorry I missed it before. I've removed it and pushed the new commit. Weird thing, it passes in my repository https://github.com/sammarshallou/moodle-auth_saml2/actions so I think it is fine, but it still shows as 'haven't completed yet' in this PR...

**Comment by danmarsden** [comment]
Thanks Sam - github actions config was wrong - I've just fixed that now and it looks like it should trigger the tests here - will see if they pass and will then merge this in - thanks!

**Pull request merged**
