### PR TITLE
Update simplesamlphp to 2.3.5

### PR DESCRIPTION
**Pull request by gbarat87**

### CODE REVIEW

**Comment by jay-oswald** [comment]
Looks good, same commits cherry-picked from my previous bump, just the 405 tests are now failing, they were passing

**Comment by gbarat87** [comment]
I have made a mistake, the upgrade step `composer remove phpmailer/phpmailer` actually include all other library.
And so an update of the phpunit one. 
So I have run again `composer install --no-dev` to remove all the unwanted library

**Comment by jay-oswald** [comment]
@gbarat87 Looks good, can you just add a version bump so it will release it with the bump

**Review by jay-oswald — APPROVED** [review]
Looks good now with the bump

**Pull request merged**
