### PR TITLE
Simplesaml 1.17.6 (don't merge yet)

### PR DESCRIPTION
**Pull request by danmarsden**
update simplesaml to 1.17.6 to help prepare for #369

### CODE REVIEW

**Comment by danmarsden** [comment]
few notes on this..

Deployed this to a testing site and the updated code seems to still work for an exisiting IDP.

Issues
1) comes bundled with a bunch of polyfills for 7.0/7.2 - we lint all files prior to deployment (and in travis) and these files fail the lint - we need to tidy up the files to remove these.

2) Behat tests failing - not sure why, but doesn't look like the php lint issues are causing that so it's likely to need further investigation.

**Comment by peterspicer-catalyst** [comment]
@danmarsden would it be easier to remove the polyfill from the composer file then rerun composer than trying to manually remove the polyfills from the resultant autoloader? Might make our maintenance easier in the long run and be cleaner about weird random dependencies.

**Comment by danmarsden** [comment]
@peterspicer-catalyst - yeah I was playing around a bit with that yesterday, looks like we're going to have some other challenges with the symfony lib version included in simplesamlphp - not just with the php-70 polyfill.

Will also be interesting to see if we can backport the security fix when it is released to the older saml2 branches for Totara support.

I guess I'll play around with this a bit more today...

**Comment by danmarsden** [comment]
further update - I just created a new branch with updated composer dependencies for php 7.2 to see if that helps - still has a few issues unfortunately!

- https://travis-ci.org/catalyst/moodle-auth_saml2/jobs/607868155#L2305

I'm tempted to look at using the simplesamlphp 1.18 RC to see if it helps us...

**Comment by danmarsden** [comment]
looks like behat failures relate to the "passive" login feature which isn't working with the latest update.

**Comment by danmarsden** [comment]
I'm also leaning towards not updating all the dependencies and just removing the stuff that fails lint.

**Comment by danmarsden** [comment]
closing this one as I have a better wip branch.

**Pull request closed without merging**
